### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by pavan4** [butchmarshall/react-native-google-nearby-connection#1]
Building an iOS app gives me the following error - 

![simulator screen shot - iphone 6 - 2018-03-12 at 12 53 57](https://user-images.githubusercontent.com/464335/37284685-7365bd38-25f4-11e8-80bf-27e2ff02d643.png)
Any pointers on how to fix this?

**Comment by butchmarshall** [comment]
Sorry - this library is Android only.  Google has released a native package Nearby Messages but not for for Nearby Connection.
